"""empty message

Revision ID: 23a9f430205f
Revises: 7aa8128f5b1d
Create Date: 2020-04-19 22:44:39.784325

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23a9f430205f'
down_revision = '7aa8128f5b1d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Show_Artist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('show_venue', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['show_venue'], ['Venue.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Show_Venue',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('show_artist', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['show_artist'], ['Artist.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Show_Venue')
    op.drop_table('Show_Artist')
    # ### end Alembic commands ###
