"""empty message

Revision ID: 948e88f6e186
Revises: 7eb5763aa038
Create Date: 2020-05-11 11:46:27.829164

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '948e88f6e186'
down_revision = '7eb5763aa038'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Artist', 'address')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Artist', sa.Column('address', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
